In [6]:
# Import all libraries needed for the tutorial

# General syntax to import specific functions in a library: 
##from (library) import (specific library function)
from pandas import DataFrame, read_csv

# General syntax to import a library but no functions: 
##import (library) as (give the library a nickname/alias)
import matplotlib.pyplot as plt
import pandas as pd #this is how I usually import pandas
import sys #only needed to determine Python version number
import matplotlib #only needed to determine Matplotlib version number

# Enable inline plotting
%matplotlib inline
print('Python version ' + sys.version)
print('Pandas version ' + pd.__version__)
print('Matplotlib version ' + matplotlib.__version__)

Python version 3.6.1 (default, Mar 23 2017, 16:49:06) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
Pandas version 0.19.2
Matplotlib version 2.0.0


In [7]:
Location = r'train.csv'
df = pd.read_csv(Location, parse_dates=['Date'])
print(type(df["Hour"][0]))

#converting the 'Hour' column to Numbers for training
for i, row in df.iterrows():  #i: dataframe index; row: each row in series format
    df['Hour'][i] = int(df['Hour'][i][:2])
    
#print(df.head())

#testing Data
Location = r'test.csv'
test_df = pd.read_csv(Location, parse_dates=['Date'])
print(type(test_df["Hour"][0]))

#converting the 'Hour' column to Numbers for testing
for i, row in test_df.iterrows():  #i: dataframe index; row: each row in series format
    test_df['Hour'][i] = int(test_df['Hour'][i][:2])

<class 'str'>


/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys


<class 'str'>


/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [8]:
#select columns here for features
flightDataPd = df[['Total','Flights','Booths','AvgWtTime']]
flightData = flightDataPd.as_matrix(columns=flightDataPd.columns[0:])
print(flightData)
#change the length of the features based on the selection
featureLength = 3
data_X_train = flightData[:,0:featureLength]
print(data_X_train)
data_y_train = flightData[:,featureLength]
print(data_y_train)
df.head()

[[424   3  11  16]
 [140   1   5   6]
 [173   1  12  10]
 ..., 
 [285   1  12  22]
 [175   1  12  11]
 [319   2  12  12]]
[[424   3  11]
 [140   1   5]
 [173   1  12]
 ..., 
 [285   1  12]
 [175   1  12]
 [319   2  12]]
[16  6 10 ..., 22 11 12]


Date Hour  Excluded  Total  Flights  Booths  AvgWtTime
0 2017-05-01    0        14    424        3      11         16
1 2017-05-01    2         3    140        1       5          6
2 2017-05-01    6         6    173        1      12         10
3 2017-05-01    7        11    340        1      12         22
4 2017-05-01    8        12    422        2      11         10

In [9]:
#select columns here for features
flightDataTestPd = test_df[['Total','Flights','Booths']]
flightDataTest = flightDataTestPd.as_matrix(columns=flightDataTestPd.columns[0:])

#change the length of the features based on the selection
data_X_test = flightDataTest[:,0:featureLength]
#data_y_test = flightDataTest[:,featureLength-1]
#print(data_y_test)
test_df.head()

Date Hour  Excluded  Total  Flights  Booths
0 2017-07-01    0        14    314        2      12
1 2017-07-01    4         7    150        1       4
2 2017-07-01    6        12    423        2      13
3 2017-07-01    7        11    323        1      16
4 2017-07-01    8        17    444        2      14

In [10]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split


#data_X_train, data_X_test, data_y_train, data_y_test = train_test_split(X, y, test_size=0, random_state=42)


# Create linear regression object
regr = linear_model.LinearRegression(normalize=True)

# Train the model using the training sets
regr.fit(data_X_train, data_y_train)

# Make predictions using the testing set
data_y_pred = regr.predict(data_X_test)
df_y_pred = pd.DataFrame(data_y_pred)
prediction_location = r'prediction.csv'
df_y_pred.to_csv(prediction_location, index=False, header=['AvgWtTime'])
# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
#print("Mean squared error: %.2f"
#      % mean_squared_error(data_y_test, data_y_pred))
# Explained variance score: 1 is perfect prediction
#print('Variance score: %.2f' % r2_score(data_y_test, data_y_pred))



Coefficients: 
 [ 0.00801276 -1.09340249  0.00238761]


In [ ]:
print(data_X_test.shape)
#print(data_y_test.shape)